# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Quotly Frontend Pipeline

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: self-hosted
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install Packages
      run: yarn install

    - name: Run Tests
      run: yarn test
    - name: Run Lint
      run: yarn lint:check

    - name: Build Project
      run: yarn build
    - uses: actions/upload-artifact@v4
      if: github.ref_name == 'main'
      with:
        name: dist-artifact
        path: dist

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref_name == 'main'
    steps:
      - name: Delete old build if it exists
        run: rm -rf /var/www/quotly/build/*
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: /var/www/quotly/build
