# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '0 12 * * 1'

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install NPM Packages
      run: npm i
    - name: Run Tests
      run: npm test
    - name: Build Project
      run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - run: cd /var/www/quotly/
      - run: git pull
      - run: npm install
      - run: npm run build