# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '0 12 * * 1'

jobs:
  build:

    runs-on: self-hosted
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install NPM Packages
      run: npm i
    - name: Run Tests
      run: npm test
    - name: Build Project
      run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull from Git and Deploy
        run: cd /var/www/quotly/build
      - name: Delete old build
        run: rm -rf /var/www/quotly/build/*
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
        
        
        